/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsSurahSearchRouteImport } from './routes/settings.surah-search'
import { Route as SettingsQrRouteImport } from './routes/settings.qr'
import { Route as SettingsGroupsRouteImport } from './routes/settings.groups'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSurahSearchRoute = SettingsSurahSearchRouteImport.update({
  id: '/surah-search',
  path: '/surah-search',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQrRoute = SettingsQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGroupsRoute = SettingsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/lookup': typeof LookupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/trash': typeof TrashRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/surah-search': typeof SettingsSurahSearchRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/lookup': typeof LookupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trash': typeof TrashRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/surah-search': typeof SettingsSurahSearchRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/lookup': typeof LookupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/trash': typeof TrashRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/surah-search': typeof SettingsSurahSearchRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/lookup'
    | '/reset-password'
    | '/settings'
    | '/trash'
    | '/settings/account'
    | '/settings/groups'
    | '/settings/qr'
    | '/settings/surah-search'
    | '/settings/system'
    | '/settings/users'
    | '/students/$studentId'
    | '/settings/'
    | '/api/public/hooks/daily-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/lookup'
    | '/reset-password'
    | '/trash'
    | '/settings/account'
    | '/settings/groups'
    | '/settings/qr'
    | '/settings/surah-search'
    | '/settings/system'
    | '/settings/users'
    | '/students/$studentId'
    | '/settings'
    | '/api/public/hooks/daily-backup'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/lookup'
    | '/reset-password'
    | '/settings'
    | '/trash'
    | '/settings/account'
    | '/settings/groups'
    | '/settings/qr'
    | '/settings/surah-search'
    | '/settings/system'
    | '/settings/users'
    | '/students/$studentId'
    | '/settings/'
    | '/api/public/hooks/daily-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  LookupRoute: typeof LookupRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TrashRoute: typeof TrashRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/surah-search': {
      id: '/settings/surah-search'
      path: '/surah-search'
      fullPath: '/settings/surah-search'
      preLoaderRoute: typeof SettingsSurahSearchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/qr': {
      id: '/settings/qr'
      path: '/qr'
      fullPath: '/settings/qr'
      preLoaderRoute: typeof SettingsQrRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/groups': {
      id: '/settings/groups'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof SettingsGroupsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsGroupsRoute: typeof SettingsGroupsRoute
  SettingsQrRoute: typeof SettingsQrRoute
  SettingsSurahSearchRoute: typeof SettingsSurahSearchRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsGroupsRoute: SettingsGroupsRoute,
  SettingsQrRoute: SettingsQrRoute,
  SettingsSurahSearchRoute: SettingsSurahSearchRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  LookupRoute: LookupRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TrashRoute: TrashRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
